return {
    Flee           = require("actions.flee"),
    Hide           = require("actions.hide"),
    CowerInHiding  = require("actions.cower_in_hiding"),
    ZigZag         = require("actions.zigzag"),
    Thrash         = require("actions.thrash"),
    EatKrill       = require("actions.eat_krill"),
    School         = require("actions.school"),
    Swim           = require("actions.swim"),
    ChaseCursor    = require("actions.chase_cursor"),
    ChasePrey      = require("actions.chase_prey"),
    HideInCloud    = require("actions.hide_in_cloud"),
    Jump           = require("actions.jump"),
    FlapTail       = require("actions.flap_tail"),
    FleeFromPred   = require("actions.flee_from_predator"),
    Puff           = require("actions.puff"),
    SlowSwim       = require("actions.slow_swim"),
    FightPlayer    = require("actions.fight_player"),
    HoverSwim      = require("actions.hover_swim"),
    EatKrillPuff          = require("actions.eat_krill_puffer"),
    FaceClosestPredator   = require("actions.face_closest_predator"),
}
