return {
    SeesPredator          = require("conditions.sees_predator"),
    SeesCursor            = require("conditions.sees_cursor"),
    SeesSmallFish         = require("conditions.sees_small_fish"),
    RockNearby            = require("conditions.rock_nearby"),
    IsHiding              = require("conditions.is_hiding"),
    IsCornered            = require("conditions.is_cornered"),
    PredatorClose         = require("conditions.predator_close"),
    IsHungry              = require("conditions.is_hungry"),
    SeesFood              = require("conditions.sees_food"),
    OtherSmallFishNearby  = require("conditions.other_small_fish_nearby"),
    OtherKrillNearby      = require("conditions.other_krill_nearby"),
    SeesNonKrill          = require("conditions.sees_non_krill"),
    SandCloudNearby       = require("conditions.sand_cloud_nearby"),
    NearSurface           = require("conditions.near_surface"),
    IsPuffed              = require("conditions.is_puffed"),
    CaughtByPlayer        = require("conditions.caught_by_player"),
    SeesKrillPuffer       = require("conditions.sees_krill"),
}
